#Loggin
logging:
  config: classpath:logback-spring-test.xml

#JWT config
jwt:
  token:
    secret: SecretKeyToGenerateAJSONWebTokens
    expiration: 10000
    prefix: Bearer
    header: Authorization
    issuer:
      info: unseen
    authorities:
      key: authorities

# Social login
social:
  login:
    google:
      url: "https://content-people.googleapis.com/v1/people/me?personFields=names,emailAddresses,photos"