spring:
  # H2 Database
  datasource:
    url: jdbc:h2:mem:testdb
    username: test
    password: test
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      database-platform: org.hibernate.dialect.H2Dialect
      ddl-auto: create-drop

#Loggin
logging:
  config: classpath:logback-spring-local.xml

#JWT config
jwt:
  token:
    secret: SecretKeyToGenerateAJSONWebTokens
    expiration: 1
    prefix: Bearer
    header: Authorization
    issuer:
      info: unseen
    authorities:
      key: authorities

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true