#Loggin
logging:
  config: classpath:logback-spring-test.xml

#JWT config
jwt:
  token:
    secret: SecretKeyToGenerateAJSONWebTokens
    expiration: 10000
    prefix: Bearer
    header: Authorization
    issuer:
      info: unseen
    authorities:
      key: authorities

# Social login
social:
  login:
    google:
      url: "https://content-people.googleapis.com/v1/people/me?personFields=names,emailAddresses,photos"
    facebook:
      url: "https://graph.facebook.com/me?fields=name,first_name,last_name,email,picture&access_token="
      picture:
        url: "https://graph.facebook.com/me/picture?redirect=0&height=500&type=normal&width=500&access_token="
    twitter:
      consumerKey: ""
      consumerSecret: ""