#Loggin
logging:
  config: classpath:logback-spring-test.xml

#JWT config
jwt:
  token:
    secret: SecretKeyToGenerateAJSONWebTokens
    expiration: 10000
    prefix: Bearer
    header: Authorization
    issuer:
      info: unseen
    authorities:
      key: authorities