{{- if .Values.cloud.config.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: spring-config-secret
type: Opaque
data:
  username: {{ .Values.cloud.config.username | b64enc }}
  password: {{ .Values.cloud.config.password | b64enc }}
{{- end }}